//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PutraJayaWebApps.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsInventory
    {
        public int InventoryID { get; set; }
        public string InventoryName { get; set; }
        public string Spesifikasi { get; set; }
        public Nullable<int> Panjang { get; set; }
        public Nullable<int> Lebar { get; set; }
        public Nullable<int> Gramasi { get; set; }
        public Nullable<decimal> PriceKg { get; set; }
        public string Category { get; set; }
    }
}
