//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PutraJayaWebApps.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsPayment
    {
        public int PaymentID { get; set; }
        public string PaymentName { get; set; }
        public string PaymentType { get; set; }
        public string PaymentRekType { get; set; }
    }
}
