//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PutraJayaWebApps.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsTransaction
    {
        public MsTransaction()
        {
            this.MsOrders = new HashSet<MsOrder>();
            this.MsTransactionInventories = new HashSet<MsTransactionInventory>();
        }
    
        public string TransactionID { get; set; }
        public string QTY { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string TransactionStatus { get; set; }
    
        public virtual ICollection<MsOrder> MsOrders { get; set; }
        public virtual ICollection<MsTransactionInventory> MsTransactionInventories { get; set; }
    }
}
